# Generated by Django 4.1.2 on 2022-12-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfRoom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('people_num', models.IntegerField()),
                ('agree', models.BooleanField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.dish')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.room')),
            ],
        ),
    ]
